### ISSUE TITLE
Turning on the extension makes the windows transparents 

### ISSUE THREAD

**Issue by radical4ever** [Selenium-H/Personalize#5]
this just happens whith the extension app and some windows. but the rest of the apps works with no problems

![Captura de pantalla de 2021-09-22 15-14-33](https://user-images.githubusercontent.com/83252104/134399186-537c7fa9-5b26-459a-a92a-775436045ddc.png)

**Comment by radical4ever** [comment]
btw the distro is fedora 34

**Comment by Selenium-H** [comment]
Please try the latest version  from [experimental](https://github.com/Selenium-H/Personalize/tree/Experimental) `branch`.

**Comment by radical4ever** [comment]
I tried it, but the issue persist. Did i need to remove config file of the older version?

**Comment by Selenium-H** [comment]
Please try the latest version  from [experimental](https://github.com/Selenium-H/Personalize/tree/Experimental) `branch`. 

> Did i need to remove config file of the older version?

If the issue still persist please try removing the `Adwaita-Personalized` folder from the `~/.themes` folder and also, please let me know the `Gtk-4` version in `Fedora 34`.

**Comment by radical4ever** [comment]
> Please try the latest version from [experimental](https://github.com/Selenium-H/Personalize/tree/Experimental) `branch`.
> 
> > Did i need to remove config file of the older version?
> 
> If the issue still persist please try removing the `Adwaita-Personalized` folder from the `~/.themes` folder and also, please let me know the `Gtk-4` version in `Fedora 34`.

Ok, so i removed Adwaita-personalized from ~/.themes but it still makes the same issue,after i change the accent color. And the Gtk-4 version is gtk4-4.2.1-1.fc34.x86_64

**Comment by Selenium-H** [comment]
Thanks for the feedback. The extension is compatible with `gtk4-4.2`. I'll try to implement generation of all versions of `gtk4` themes.  In the mean time please try the following -

Disable and remove the extension. 
Remove `Adwaita-Personalized` from the `~/.themes` folder.

Reinstall it from the [Experimental](https://github.com/Selenium-H/Personalize/tree/Experimental) `branch`. 
Restart `GNOME Shell`  for `Xorg` or log out and log in back for `wayland`.

Open the `extension preferences` and select a different accent color.
Press the `reload` button on the left of the headerbar.  

Open the file `~/.themes/Adwaita-Personalized/gtk-4.0/gtk.css`.
Check if `line 15` contains `/*Theme_Variant*/@import url("resource:///org/gtk/libgtk/theme/Default/Default-dark.css");` 
If so please change it to `/*Theme_Variant*/@import url("resource:///org/gtk/libgtk/theme/Adwaita/Adwaita.css");` manually.

Enable the extension. 

If the issue is fixed please report here.

**Comment by radical4ever** [comment]
Yes!! The issue is fixed!! I redownloaded and reinstalled checked ~/.themes/Adwaita-Personalized/gtk-4.0/gtk.css and its already modified like:  *Theme_Variant*/@import url("resource:///org/gtk/libgtk/theme/Adwaita/Adwaita.css"). Thank you for all the support!!
